name: Build and Deploy Wisecow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY || secrets.DOCKER_USERNAME }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/wisecow:latest
          ${{ secrets.DOCKER_USERNAME }}/wisecow:${{ github.sha }}
    
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
    
    - name: Configure Kubernetes config
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
        chmod 600 $HOME/.kube/config
    
    - name: Update Kubernetes manifests
      run: |
        # Load .env file if it exists
        if [ -f .env ]; then
          export $(grep -v '^#' .env | xargs)
        fi
        
        # Use DOCKER_REGISTRY from .env if available, otherwise use from GitHub
        REGISTRY="${DOCKER_REGISTRY:-${{ env.DOCKER_REGISTRY }}}"
        
        # Update the deployment.yaml with the correct image
        sed -i "s|image: \${{ env.DOCKER_REGISTRY }}/wisecow:latest|image: ${REGISTRY}/wisecow:${{ github.sha }}|g" k8s/deployment.yaml
        
        # Debug: Let's see what the file looks like after substitution
        echo "Updated deployment.yaml:"
        cat k8s/deployment.yaml
    
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml