name: Build and Deploy Wisecow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY || secrets.DOCKER_USERNAME }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/wisecow:latest
          ${{ secrets.DOCKER_USERNAME }}/wisecow:${{ github.sha }}
    
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
    
    - name: Configure Kubernetes config
      run: |
        mkdir -p $HOME/.kube
        
        echo "Attempting to write config with base64 decoding first..."
        if echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config 2>/dev/null; then
          echo "Successfully decoded KUBE_CONFIG with base64"
        else
          echo "Base64 decoding failed, writing KUBE_CONFIG directly"
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
        fi
        
        chmod 600 $HOME/.kube/config
        
        echo "Kubeconfig file created. Checking if it exists:"
        ls -la $HOME/.kube/
    
    - name: Direct update of deployment manifest
      run: |
        sed -i "s|image: .*|image: ${{ env.DOCKER_REGISTRY }}/wisecow:${{ github.sha }}|g" k8s/deployment.yaml
        
        echo "Deployment after update:"
        cat k8s/deployment.yaml
    
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml