name: Deploy Wisecow (New)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_USERNAME }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/wisecow:latest
          ${{ secrets.DOCKER_USERNAME }}/wisecow:${{ github.sha }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1

    - name: Create kubeconfig file
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Test kubeconfig
      run: kubectl config view --minify

    - name: Update deployment image
      run: |
        sed -i "s|image: .*|image: ${{ env.DOCKER_REGISTRY }}/wisecow:${{ github.sha }}|g" k8s/deployment.yaml
        echo "Updated deployment file:"
        cat k8s/deployment.yaml

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml
