name: Deploy Wisecow (New)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY || secrets.DOCKER_USERNAME }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/wisecow:latest
          ${{ secrets.DOCKER_USERNAME }}/wisecow:${{ github.sha }}
    
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
    
    - name: Create kubeconfig file safely
      run: |
        mkdir -p $HOME/.kube
        
        # Write the raw config without any decoding
        echo "Creating kubeconfig file directly without decoding..."
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config
        
        # Debug: Check if the file exists
        echo "Kubeconfig file created at: $HOME/.kube/config"
        ls -la $HOME/.kube/
    
    - name: Test kubectl config
      run: |
        # Test if kubectl can use the config without actually connecting
        kubectl config view --minify
        
    - name: Update deployment manifest
      run: |
        # Directly replace the image without using .env file
        sed -i "s|image: .*|image: ${{ env.DOCKER_REGISTRY }}/wisecow:${{ github.sha }}|g" k8s/deployment.yaml
        
        # Debug output
        echo "Deployment after update:"
        cat k8s/deployment.yaml
    
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml